// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: ''),
    appId: '1:916876344507:web:75e638cd53fc998c5b3d9e',
    messagingSenderId: '916876344507',
    projectId: 'parking-manager-app-iot',
    authDomain: 'parking-manager-app-iot.firebaseapp.com',
    storageBucket: 'parking-manager-app-iot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY', defaultValue: ''),
    appId: '1:916876344507:android:f5becd2f5e9b15d05b3d9e',
    messagingSenderId: '916876344507',
    projectId: 'parking-manager-app-iot',
    storageBucket: 'parking-manager-app-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: ''),
    appId: '1:916876344507:ios:01506d8dc697ac2d5b3d9e',
    messagingSenderId: '916876344507',
    projectId: 'parking-manager-app-iot',
    storageBucket: 'parking-manager-app-iot.firebasestorage.app',
    iosBundleId: 'com.example.parkingManagerAppIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_MACOS_API_KEY', defaultValue: ''),
    appId: '1:916876344507:ios:01506d8dc697ac2d5b3d9e',
    messagingSenderId: '916876344507',
    projectId: 'parking-manager-app-iot',
    storageBucket: 'parking-manager-app-iot.firebasestorage.app',
    iosBundleId: 'com.example.parkingManagerAppIot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WINDOWS_API_KEY', defaultValue: ''),
    appId: '1:916876344507:web:6a5e14b31b303a115b3d9e',
    messagingSenderId: '916876344507',
    projectId: 'parking-manager-app-iot',
    authDomain: 'parking-manager-app-iot.firebaseapp.com',
    storageBucket: 'parking-manager-app-iot.firebasestorage.app',
  );
}
